name: h3_dart
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.2
homepage: https://github.com/festelo/h3_dart

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  ffi: ^2.0.1
  h3_ffi: ^0.6.2
  h3_web: ^0.6.1
  h3_common: ^0.6.1
  geojson2h3: ^0.6.1

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.3
