name: h3_dart
description: The package provides Dart version of the H3 Core library, a hexagon-based geographic grid system
version: 0.5.0-dev
homepage: https://github.com/festelo/h3_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  test: ^1.21.2
  lints: ^2.0.0
  ffigen: ^4.1.2
  collection: ^1.15.0