name: h3_flutter
description: Bindings to H3 library
version: 0.1.0
homepage: https://github.com/festelo/h3_flutter

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.example.h3_flutter
        pluginClass: H3FlutterPlugin
      ios:
        pluginClass: H3FlutterPlugin