name: example
description: An absolute bare-bones web app.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  h3_dart:
    path: ../..

dev_dependencies:
  lints: ^1.0.0
