name: h3_flutter
description: The package provides Flutter version of the H3 Core library, a hexagon-based geographic grid system
version: 0.6.0-dev
homepage: https://github.com/festelo/h3_dart

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  h3_dart: ^0.6.0-dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.h3_flutter
        pluginClass: H3FlutterPlugin
      ios:
        pluginClass: H3FlutterPlugin
      macos:
        pluginClass: H3FlutterPlugin
