name: Publish to pub.dev

on:
  push:

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# secrets.PUB_CREDENTIAL_JSON taken from "~/Library/Application Support/dart/pub-credentials.json"

jobs:
  publish_h3_dart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: festelo/actions-flutter-pub-publisher@master
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: false
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./h3_dart

  publish_h3_flutter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: festelo/actions-flutter-pub-publisher@master
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./h3_flutter