name: Publish to pub.dev, create tag and release

on:
  push:

concurrency:
  group: publish-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# secrets.PUB_CREDENTIAL_JSON taken from "~/Library/Application Support/dart/pub-credentials.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package: [h3_common, geojson2h3, h3_ffi, h3_web, h3_dart, h3_flutter]
        include:
          - package: h3_common
            release_name: "H3 Common"
          - package: geojson2h3
            release_name: "Geojson2H3"
          - package: h3_ffi
            release_name: "H3 Ffi"
          - package: h3_web
            release_name: "H3 Web"
          - package: h3_dart
            release_name: "H3 Dart"
          - package: h3_flutter
            release_name: "H3 Flutter"
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: stable
          architecture: x64

      - name: Get version
        run: echo "VERSION=$(dart scripts/get_package_version.dart)" >> $GITHUB_ENV
        env:
          target:  ${{ matrix.package }}

      - id: get_existing_release
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ matrix.package }}_${{ env.VERSION }}
        continue-on-error: true

      - name: Publish to pub
        uses: festelo/actions-flutter-pub-publisher@master
        with:
          credential: ${{ secrets.PUB_CREDENTIAL_JSON }}
          flutter_package: true
          skip_test: true
          dry_run: ${{ github.ref != 'refs/heads/master' }}
          package_directory: ./${{ matrix.package }}
        if: steps.get_existing_release.outputs.id == null

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "${{ matrix.release_name }} v${{ env.VERSION }}"
          automatic_release_tag: "${{ matrix.package }}_${{ env.VERSION }}"
        if: steps.get_existing_release.outputs.id == null && github.ref == 'refs/heads/master'
  