name: Pubspec Checks

on: 
  push:
  pull_request:

concurrency:
  group: pubspec_checks-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  h3_dart_check:
    name: Check h3_dart version is the same in ./h3_dart and ./h3_flutter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1.3
      with:
        sdk: stable
        architecture: x64

    - name: Check h3_dart version is synchronized
      run: dart scripts/sync_h3_dart_version.dart
      env:
        test: true