name: Tests

on: 
  push:
  pull_request:
  schedule:
    # runs the CI everyday at 10AM
    - cron: "0 10 * * *"

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  h3_ffi_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: [stable, beta, dev]
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3
        with:
          sdk: ${{ matrix.sdk }}
          architecture: x64

      - name: Install coverage tool
        run: dart pub global activate coverage
  
      - name: Prepare tests
        run: sh scripts/prepare_tests.sh

      - name: Override dependencies
        run: dart scripts/dependency_override.dart

      - name: Install dependencies
        run: dart pub get
        working-directory: ./h3_ffi

      - name: Analyze
        run: dart analyze
        working-directory: ./h3_ffi

      - name: Run tests
        run: dart pub global run coverage:test_with_coverage
        working-directory: ./h3_ffi

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./h3_ffi/coverage/lcov.info
          flags: h3_ffi


  h3_flutter_test_desktop:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Install linux dependencies
      run: sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev
      if: matrix.os == 'ubuntu-latest'

    - name: Setup subosito/flutter-action@v2
      uses: subosito/flutter-action@v2
      with:
        channel: beta
        architecture: x64

    - name: Enable linux
      run: flutter config --enable-linux-desktop

    - name: Enable macos
      run: flutter config --enable-macos-desktop

    - name: Enable windows
      run: flutter config --enable-windows-desktop
    
    - name: Override dependencies
      run: dart scripts/dependency_override.dart

    - name: Pub get
      run: "flutter pub get"
      working-directory: ./h3_flutter

    - name: Analyze
      run: "flutter analyze"
      working-directory: ./h3_flutter

    - name: Run tests (linux)
      run: | 
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          flutter test integration_test/app_test.dart
      working-directory: ./h3_flutter/example
      if: matrix.os == 'ubuntu-latest'

    - name: Run tests
      run: flutter test integration_test/app_test.dart
      working-directory: ./h3_flutter/example